export enum GameStatus {
	COMPLETED = 'COMPLETED',
	CANCELED = 'CANCELED',
	IN_PROGRESS = 'IN_PROGRESS',
	PLANNED = 'PLANNED'
}

export enum GameDifficulty {
	ONE = 1,
	TWO = 2,
	THREE = 3,
	FOUR = 4,
	FIVE = 5,
}

export enum GameGenre {
	ABSTRACT = "ABSTRACT",
	AREA_CONTROL = "AREA_CONTROL",
	CARD = "CARD",
	COOPERATIVE = "COOPERATIVE",
	DECKBUILDER = "DECKBUILDER",
	DUNGEON_CRAWLER = "DUNGEON_CRAWLER",
	ENGINE_BUILDER = "ENGINE_BUILDER",
	EURO = "EURO",
	FAMILY = "FAMILY",
	PARTY = "PARTY",
	STRATEGY = "STRATEGY",
	WARGAME = "WARGAME",
}