name: Deploy to server
run-name: deploying
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_TIMEWEB_SWEATCLUB_ID_RSA_PRIVATE_KEY }}
          port: 22
          script: |
            cp /var/www/env-files/sweatclub/.env /var/www/pttrulez-subdomains/sweatclub/.env
            cp /var/www/env-files/sweatclub/.env.apps.api /var/www/pttrulez-subdomains/sweatclub/apps/api/.env
            cp /var/www/env-files/sweatclub/.env.packages.database /var/www/pttrulez-subdomains/sweatclub/packages/database/.env
            cd /var/www/pttrulez-subdomains/sweatclub
            git pull
            docker-compose up -d --build
